/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Enzo
 */
public class VentanaPacientes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPacientes2
     */
    public VentanaPacientes() {
        initComponents();
        setSize(825, 475);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        campoBuscar = new javax.swing.JTextField();
        labelBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        labelDomicilio = new javax.swing.JLabel();
        campoNom = new javax.swing.JTextField();
        campoApe = new javax.swing.JTextField();
        campoTel = new javax.swing.JTextField();
        campoDom = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);
        jPanel2.add(campoBuscar);
        campoBuscar.setBounds(90, 10, 160, 30);

        labelBuscar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelBuscar.setText("Buscar");
        jPanel2.add(labelBuscar);
        labelBuscar.setBounds(14, 14, 60, 30);

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPacientes);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 510, 404);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(280, 0, 540, 470);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelNombre.setText("Nombre");
        jPanel1.add(labelNombre);
        labelNombre.setBounds(20, 20, 70, 30);

        labelApellido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelApellido.setText("Apellido");
        jPanel1.add(labelApellido);
        labelApellido.setBounds(20, 80, 70, 30);

        labelTel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelTel.setText("Tel/Cel");
        jPanel1.add(labelTel);
        labelTel.setBounds(20, 140, 70, 30);

        labelDomicilio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelDomicilio.setText("Domicilio");
        jPanel1.add(labelDomicilio);
        labelDomicilio.setBounds(20, 200, 80, 30);
        jPanel1.add(campoNom);
        campoNom.setBounds(130, 20, 90, 30);
        jPanel1.add(campoApe);
        campoApe.setBounds(130, 80, 90, 30);
        jPanel1.add(campoTel);
        campoTel.setBounds(130, 140, 90, 30);
        jPanel1.add(campoDom);
        campoDom.setBounds(130, 200, 90, 30);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnGuardar.setText("Guardar");
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(10, 280, 100, 40);

        btnBorrar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBorrar.setText("Borrar");
        jPanel1.add(btnBorrar);
        btnBorrar.setBounds(130, 280, 110, 40);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar);
        btnModificar.setBounds(10, 350, 99, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 270, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField campoApe;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JTextField campoDom;
    private javax.swing.JTextField campoNom;
    private javax.swing.JTextField campoTel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTel;
    private javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables
}
