/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Enzo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    public VentanaPrincipal() {
        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(this);
        setResizable(false);
    }
    public class ImgUtils {

    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTurnos = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnVade = new javax.swing.JButton();
        btnFichMedica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        btnTurnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTurnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/turnos.png"))); // NOI18N
        btnTurnos.setText("Turnos");
        btnTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTurnos);
        btnTurnos.setBounds(430, 30, 140, 50);

        btnPacientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1458530871_PatientMale.png"))); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPacientes);
        btnPacientes.setBounds(600, 30, 160, 50);

        btnVade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book.png"))); // NOI18N
        btnVade.setText("Vademecum");
        btnVade.setBorder(null);
        btnVade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVadeActionPerformed(evt);
            }
        });
        jPanel1.add(btnVade);
        btnVade.setBounds(220, 30, 160, 50);

        btnFichMedica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFichMedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha medica.png"))); // NOI18N
        btnFichMedica.setText("Fichas Medicas");
        btnFichMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichMedicaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFichMedica);
        btnFichMedica.setBounds(10, 30, 190, 50);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 4, 780, 590);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFichMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichMedicaActionPerformed
        VentanaFicha VFM= new VentanaFicha();
        VFM.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnFichMedicaActionPerformed

    private void btnTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnosActionPerformed
        VentanaTurnos miVentanaTurnos= new VentanaTurnos();
        miVentanaTurnos.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnTurnosActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        VentanaPacientes miVentanaPacientes= new VentanaPacientes();
        miVentanaPacientes.setVisible(true);
       // this.dispose();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnVadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVadeActionPerformed
        VentanaVademecum miVentanaVademecum= new VentanaVademecum();
        miVentanaVademecum.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnVadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFichMedica;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnTurnos;
    private javax.swing.JButton btnVade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
