/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Enzo
 */
public class VentanaFicha extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFicha2
     */
    public VentanaFicha() {
        initComponents();
        setSize(1125, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelApe = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelDire = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelDbt = new javax.swing.JLabel();
        campoApe = new javax.swing.JTextField();
        campoNom = new javax.swing.JTextField();
        campoDire = new javax.swing.JTextField();
        campoTel = new javax.swing.JTextField();
        campoEdad = new javax.swing.JTextField();
        comboHiperhidrosis = new javax.swing.JComboBox<>();
        labelCardiacas = new javax.swing.JLabel();
        labelAnticuagulado = new javax.swing.JLabel();
        comboTalon = new javax.swing.JComboBox<>();
        comboCardiacas = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelMicosis = new javax.swing.JLabel();
        comboMicosis = new javax.swing.JComboBox<>();
        labelOnicocriptosis = new javax.swing.JLabel();
        comboAnticuagulado = new javax.swing.JComboBox<>();
        labelTalon1 = new javax.swing.JLabel();
        comboDbt = new javax.swing.JComboBox<>();
        labelHiperquratosis = new javax.swing.JLabel();
        comboHiperqueratosis = new javax.swing.JComboBox<>();
        labelHiperhidrosis = new javax.swing.JLabel();
        comboEdema = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        comboOnicocriptosis = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        labelDClinicos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDClinicos = new javax.swing.JTextArea();
        labelPatologias = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaPatologias = new javax.swing.JTextArea();
        labelTratamiento = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaEvolucion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaTratamiento = new javax.swing.JTextArea();
        labelEvolucion = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        labelTalon2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        labelApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelApe.setText("Apellido");
        jPanel1.add(labelApe);
        labelApe.setBounds(10, 30, 70, 22);

        labelNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNom.setText("Nombre");
        jPanel1.add(labelNom);
        labelNom.setBounds(300, 30, 80, 22);

        labelDire.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDire.setText("Dirección");
        jPanel1.add(labelDire);
        labelDire.setBounds(550, 40, 60, 22);

        labelTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTel.setText("Tel/Cel");
        jPanel1.add(labelTel);
        labelTel.setBounds(840, 30, 55, 22);

        labelEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEdad.setText("Edad");
        jPanel1.add(labelEdad);
        labelEdad.setBounds(10, 90, 50, 22);

        labelDbt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDbt.setText("DBT");
        jPanel1.add(labelDbt);
        labelDbt.setBounds(550, 110, 50, 22);

        campoApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(campoApe);
        campoApe.setBounds(130, 30, 110, 30);

        campoNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(campoNom);
        campoNom.setBounds(420, 30, 100, 30);

        campoDire.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(campoDire);
        campoDire.setBounds(640, 40, 110, 30);

        campoTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(campoTel);
        campoTel.setBounds(970, 30, 110, 30);

        campoEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(campoEdad);
        campoEdad.setBounds(130, 90, 110, 30);

        comboHiperhidrosis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboHiperhidrosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(comboHiperhidrosis);
        comboHiperhidrosis.setBounds(130, 210, 110, 30);

        labelCardiacas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCardiacas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCardiacas.setText("Afecciones Cardíacas");
        jPanel1.add(labelCardiacas);
        labelCardiacas.setBounds(830, 100, 130, 22);

        labelAnticuagulado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAnticuagulado.setText("Anticuagulado");
        jPanel1.add(labelAnticuagulado);
        labelAnticuagulado.setBounds(290, 90, 120, 22);

        comboTalon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboTalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(comboTalon);
        comboTalon.setBounds(640, 190, 110, 30);

        comboCardiacas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboCardiacas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(comboCardiacas);
        comboCardiacas.setBounds(970, 100, 110, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(800, 10, 10, 250);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(280, 10, 10, 250);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(530, 10, 10, 250);

        labelMicosis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMicosis.setText("Micosis");
        jPanel1.add(labelMicosis);
        labelMicosis.setBounds(10, 150, 80, 22);

        comboMicosis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboMicosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inter Digital", "Ungueal", "Plantar", " " }));
        jPanel1.add(comboMicosis);
        comboMicosis.setBounds(130, 150, 110, 30);

        labelOnicocriptosis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelOnicocriptosis.setText("Onicocriptosis");
        jPanel1.add(labelOnicocriptosis);
        labelOnicocriptosis.setBounds(290, 160, 120, 22);

        comboAnticuagulado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboAnticuagulado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(comboAnticuagulado);
        comboAnticuagulado.setBounds(420, 90, 100, 30);

        labelTalon1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTalon1.setText("Talón");
        jPanel1.add(labelTalon1);
        labelTalon1.setBounds(550, 170, 60, 22);

        comboDbt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboDbt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(comboDbt);
        comboDbt.setBounds(640, 110, 110, 30);

        labelHiperquratosis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelHiperquratosis.setText("Hiperqueratosis");
        jPanel1.add(labelHiperquratosis);
        labelHiperquratosis.setBounds(830, 170, 100, 22);

        comboHiperqueratosis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboHiperqueratosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lateral", "Superior", "Metatarsal" }));
        jPanel1.add(comboHiperqueratosis);
        comboHiperqueratosis.setBounds(970, 170, 110, 30);

        labelHiperhidrosis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelHiperhidrosis.setText("HiperHidrosis");
        jPanel1.add(labelHiperhidrosis);
        labelHiperhidrosis.setBounds(10, 220, 110, 22);

        comboEdema.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboEdema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(comboEdema);
        comboEdema.setBounds(420, 210, 100, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Edema");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 220, 60, 22);

        comboOnicocriptosis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboOnicocriptosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(comboOnicocriptosis);
        comboOnicocriptosis.setBounds(420, 150, 100, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        labelDClinicos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDClinicos.setText("Datos Clínicos");
        jPanel2.add(labelDClinicos);
        labelDClinicos.setBounds(20, 10, 130, 22);

        areaDClinicos.setColumns(20);
        areaDClinicos.setRows(5);
        jScrollPane1.setViewportView(areaDClinicos);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 200, 160);

        labelPatologias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPatologias.setText("Otras Patologías");
        jPanel2.add(labelPatologias);
        labelPatologias.setBounds(250, 10, 140, 22);

        areaPatologias.setColumns(20);
        areaPatologias.setRows(5);
        jScrollPane2.setViewportView(areaPatologias);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(240, 40, 200, 160);

        labelTratamiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTratamiento.setText("Tratamiento");
        jPanel2.add(labelTratamiento);
        labelTratamiento.setBounds(470, 10, 120, 22);

        areaEvolucion.setColumns(20);
        areaEvolucion.setRows(5);
        jScrollPane3.setViewportView(areaEvolucion);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(710, 40, 210, 160);

        areaTratamiento.setColumns(20);
        areaTratamiento.setRows(5);
        jScrollPane4.setViewportView(areaTratamiento);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(470, 40, 210, 160);

        labelEvolucion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEvolucion.setText("Evolución");
        jPanel2.add(labelEvolucion);
        labelEvolucion.setBounds(720, 10, 90, 22);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(220, 10, 10, 180);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(690, 10, 10, 180);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(450, 10, 10, 180);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 270, 930, 210);

        labelTalon2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTalon2.setText("Agrietado");
        jPanel1.add(labelTalon2);
        labelTalon2.setBounds(550, 200, 80, 14);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1458532674_floppy_disk_save.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(10, 500, 150, 40);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modify.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        jPanel1.add(btnModificar);
        btnModificar.setBounds(190, 500, 170, 40);

        btnBorrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1458532731_trash.png"))); // NOI18N
        btnBorrar.setText("BORRAR");
        jPanel1.add(btnBorrar);
        btnBorrar.setBounds(410, 500, 140, 40);

        btnMostrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1458516970_medical-06.png"))); // NOI18N
        btnMostrar.setText("MOSTRAR FICHAS");
        jPanel1.add(btnMostrar);
        btnMostrar.setBounds(710, 500, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFicha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDClinicos;
    private javax.swing.JTextArea areaEvolucion;
    private javax.swing.JTextArea areaPatologias;
    private javax.swing.JTextArea areaTratamiento;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JTextField campoApe;
    private javax.swing.JTextField campoDire;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoNom;
    private javax.swing.JTextField campoTel;
    private javax.swing.JComboBox<String> comboAnticuagulado;
    private javax.swing.JComboBox<String> comboCardiacas;
    private javax.swing.JComboBox<String> comboDbt;
    private javax.swing.JComboBox<String> comboEdema;
    private javax.swing.JComboBox<String> comboHiperhidrosis;
    private javax.swing.JComboBox<String> comboHiperqueratosis;
    private javax.swing.JComboBox<String> comboMicosis;
    private javax.swing.JComboBox<String> comboOnicocriptosis;
    private javax.swing.JComboBox<String> comboTalon;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelAnticuagulado;
    private javax.swing.JLabel labelApe;
    private javax.swing.JLabel labelCardiacas;
    private javax.swing.JLabel labelDClinicos;
    private javax.swing.JLabel labelDbt;
    private javax.swing.JLabel labelDire;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEvolucion;
    private javax.swing.JLabel labelHiperhidrosis;
    private javax.swing.JLabel labelHiperquratosis;
    private javax.swing.JLabel labelMicosis;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelOnicocriptosis;
    private javax.swing.JLabel labelPatologias;
    private javax.swing.JLabel labelTalon1;
    private javax.swing.JLabel labelTalon2;
    private javax.swing.JLabel labelTel;
    private javax.swing.JLabel labelTratamiento;
    // End of variables declaration//GEN-END:variables
}
